### ISSUE TITLE
get_algorithm( ) fails for some

### ISSUE THREAD

**Issue by microprediction** [msu-coinlab/pymoo#101]
get_algorithm() seems to work for ["brkga_cube", nelder_cube, cmaes_cube, pattern_cube] 

However when I try any other (e.g. [nsga2_cube, nsga3_cube,\
    rnsga3_cube, rnsga2_cube, unsga3_cube, moead_cube, ctaea_cube, de_cube])

I get his error. 

Traceback (most recent call last):
  File "/Users/petercotton/github/tuneup/studies/pymoo_horse_race.py", line 104, in <module>
    f_values = [ solver(objective,scale,n_trials=n_benchmark_trials) for solver in SOLVERS ]
  File "/Users/petercotton/github/tuneup/studies/pymoo_horse_race.py", line 104, in <listcomp>
    f_values = [ solver(objective,scale,n_trials=n_benchmark_trials) for solver in SOLVERS ]
  File "/Users/petercotton/github/tuneup/tuneup/pymoocube.py", line 38, in nsga3_cube
    return pymoo_cube(objective=objective,scale=scale ,n_trials=n_trials, method_name="nsga3")
  File "/Users/petercotton/github/tuneup/tuneup/pymoocube.py", line 54, in pymoo_cube
    algorithm = get_algorithm(method_name)
  File "/Users/petercotton/virtual-envs/tuneup/lib/python3.7/site-packages/pymoo/factory.py", line 92, in get_algorithm
    return get_from_list(get_algorithm_options(), name, args, {**d, **kwargs})
  File "/Users/petercotton/virtual-envs/tuneup/lib/python3.7/site-packages/pymoo/factory.py", line 48, in get_from_list
    return clazz(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'ref_dirs'

**Comment by julesy89** [comment]
NSGA3 needs `ref_dirs` as an initial argument. Same for `MOEAD`. Both algorithms are reference-direction based.
Reference Direction could be created using the `get_reference_directions ` method. 
The settings are different depending on the number of objectives. 

For instance,

```
ref_dirs = get_reference_directions("das-dennis", 3, n_partitions=12)
algorithm = get_algorithm("nsga3", ref_dirs)
```

**Comment by microprediction** [comment]
Thanks a lot.

**Comment by microprediction** [comment]
File "/Users/petercotton/virtual-envs/tuneup/lib/python3.7/site-packages/pymoo/factory.py", line 92, in get_algorithm
    return get_from_list(get_algorithm_options(), name, args, {**d, **kwargs})
  File "/Users/petercotton/virtual-envs/tuneup/lib/python3.7/site-packages/pymoo/factory.py", line 48, in get_from_list
    return clazz(*args, **kwargs)
  File "/Users/petercotton/virtual-envs/tuneup/lib/python3.7/site-packages/pymoo/algorithms/nsga3.py", line 89, in __init__
    survival = ReferenceDirectionSurvival(ref_dirs)
  File "/Users/petercotton/virtual-envs/tuneup/lib/python3.7/site-packages/pymoo/algorithms/nsga3.py", line 127, in __init__
    self.ideal_point = np.full(ref_dirs.shape[1], np.inf)
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by julesy89** [comment]
Not sure what you are doing.

```
from pymoo.factory import get_problem, get_reference_directions, get_algorithm
from pymoo.optimize import minimize
from pymoo.visualization.scatter import Scatter

# create the reference directions to be used for the optimization
ref_dirs = get_reference_directions("das-dennis", 3, n_partitions=12)


algorithm = get_algorithm("nsga3", ref_dirs)

# execute the optimization
res = minimize(get_problem("dtlz1"),
               algorithm,
               seed=1,
               termination=('n_gen', 600))

Scatter().add(res.F).show()

```

Works.

**Comment by microprediction** [comment]
Probably I'm doing something daft, but I'm merely trying to instantiate the full list of algorithms. 
It seems that the get_reference_directions doesn't instantiate ref_dirs.shape[1] to the satisfaction of some algos. Perhaps I'm using das-dennis inappropriately? 

https://github.com/microprediction/tuneup/blob/master/tuneup/trivariatesingleobjectivesolvers/pymoocube.py

**Comment by julesy89** [comment]
As said `REF_DIRS` depends on the number of objectives. Reference directions for 1 objective do not really makes sense.
The reference direction method's second argument shall be the number of objectives.
