### ISSUE TITLE
VisibleDeprecationWarning on Crossover()

### ISSUE THREAD

**Issue by xplsek03** [msu-coinlab/pymoo#150]
Hello, thanks again for this library. Saved me two lifes.

I have this problem: 

```Problem.__init__(n_var=1, n_obj=3, n_constr=0, elementwise_evaluation=False)```

There are 3 objectives  - float. I am working with custom pathos process Pool, as problem.pool. 
```
Problem _evaluate(x):

        # custom evaluation, per process
        def custom_eval(member):
            ...
            return np.array([obj1, obj2, obj3], dtype=float)

        # evaluate member by member
        exes = [x[a][0] for a in range(len(x))]
        try:
            F = self.pool.map(custom_eval, exes)
            out["F"] = np.column_stack(F)
```
I got inspired by this: https://pymoo.org/customization/custom.html, for example this is part of my Sampling:
```
_do( ... ):
    ...
    X[i, 0] = { some stuff }
```

On evaluation I am getting:  
```
File "/home/kali/Desktop/venv/lib/python3.8/site-packages/pymoo/model/evaluator.py", line 103, in _eval
    pop.set(key, val)
  File "/home/kali/Desktop/venv/lib/python3.8/site-packages/pymoo/model/population.py", line 58, in set
    raise Exception("Population Set Attribute Error: Number of values and population size do not match!")
Exception: Population Set Attribute Error: Number of values and population size do not match!
```
Any idea what is going wrong? Thanks for reply.

**Comment by xplsek03** [comment]
update:

when I tried to hold the same array format on output as on input, I used np.row_stack instead of column_stack. Now I have:

```
KeyboardInterrupt
/home/kali/Desktop/venv/lib/python3.8/site-packages/pymoo/model/population.py:84: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  res = [np.array(e) for e in res]
Process ShophackerProcess-1:
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/kali/Desktop/BC-ROZHRANI/task/shophacker.py", line 62, in run
    minimize(problem, algorithm, ('n_gen', sys.maxsize if konfig['nekonecno'] else konfig['generace']), seed=1, verbose=True)
  File "/home/kali/Desktop/venv/lib/python3.8/site-packages/pymoo/optimize.py", line 85, in minimize
    res = algorithm.solve()
  File "/home/kali/Desktop/venv/lib/python3.8/site-packages/pymoo/model/algorithm.py", line 226, in solve
    self._solve(self.problem)
  File "/home/kali/Desktop/venv/lib/python3.8/site-packages/pymoo/model/algorithm.py", line 321, in _solve
    self.next()
  File "/home/kali/Desktop/venv/lib/python3.8/site-packages/pymoo/model/algorithm.py", line 246, in next
    self._next()
  File "/home/kali/Desktop/venv/lib/python3.8/site-packages/pymoo/algorithms/genetic_algorithm.py", line 114, in _next
    self.pop = self.survival.do(self.problem, self.pop, self.pop_size, algorithm=self,
  File "/home/kali/Desktop/venv/lib/python3.8/site-packages/pymoo/model/survival.py", line 120, in do
    survivors = self._do(problem, pop, n_survive, **kwargs)
  File "/home/kali/Desktop/venv/lib/python3.8/site-packages/pymoo/algorithms/nsga2.py", line 128, in _do
    F = pop.get("F").astype(float, copy=False)
ValueError: setting an array element with a sequence.
```
I dont know if it leads somewhere, but it's something.

**Comment by xplsek03** [comment]
update: I used ```np.row_stack``` on output of ```Problem._evaluate```. I tracked my problem to custom Crossover() operator:

```
  def _do(self, problem, X, **kwargs):
 
        _, n_matings, n_var = X.shape
        Y = np.full_like(X, None, dtype=object)

        for k in range(n_matings):
            
            # get parents
            a, b = X[0, k, 0], X[1, k, 0]

            # copy offsprings
            offspring_a = copy.deepcopy(a)
            offspring_b = copy.deepcopy(b)

            .. make some modifications on offsprings ...
            offspring_mods()

            Y[0, k, 0], Y[1, k, 0] = syn_a, syn_b
            
        return Y
```
Doesn't raise the error when not using copy.deepcopy, wonder why.

**Comment by julesy89** [comment]
The error indicates that the `Sampling` implementation returns the wrong shape. Make sure that the shape is `n_samples` x `n_var`. Otherwise, I would need more context on what you are trying to achieve.

**Comment by xplsek03** [comment]
I dont wanna waste your time but I shared to you my repo containing the Sampling operator anyway: its in module task.genetix.operatory (because of debug I am pretty sure it returns the same shape but I might be wrong).
If you dont feel like looking at it just ignore this message, I will remove the access in 10 days. If you feel like looking at it and want some beer money, just let me know. Thanks.

**Comment by julesy89** [comment]
Looking at a whole repo would indeed take too long. If you share a small piece of code here that helps me to reproduce your error, I will have a look.

**Comment by xplsek03** [comment]
Not very sure what the problem was, but it seems exception only spawned when some process from pathos multiprocessing pool wasn't ended properly. Sorry to bother, closing now.
