### ISSUE TITLE
`MixedVariableMutation` crashes in `scipy==1.7.0`

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [msu-coinlab/pymoo#167]
Below is a minimal implementation that reproduces the bug, the code works well in `scipy==1.6.3`, bug crashes with `ValueError: Unsupported dtype object` in `scipy==1.7.0`, I'm using `pymoo==4.2.2`

```python
import numpy as np
from pymoo.model.problem import Problem
from pymoo.optimize import minimize
from pymoo.factory import get_algorithm
from pymoo.operators.mixed_variable_operator import MixedVariableMutation
from pymoo.factory import get_mutation


class MyProblem(Problem):
    def __init__(self):
        super().__init__(n_var=2,
                         n_obj=1,
                         n_constr=0,
                         xl=np.array([-2, -2]),
                         xu=np.array([2, 2]),
                         )

    def _evaluate(self, x, out, *args, **kwargs):
        out['F'] = (x ** 2).sum(axis = 1, keepdims = True)


mask = ['real', 'real']
mutation = MixedVariableMutation(mask, {
    'real' : get_mutation('real_pm', eta = 20), 
    'int'  : get_mutation('int_pm',  eta = 20)
})
problem   = MyProblem()
algorithm = get_algorithm('ga', pop_size = 100, mutation = mutation)
res       = minimize(problem, algorithm, ("n_gen", 100), verbose=True, seed=1)
print(res.X)
```

This is the error message

```

Compiled modules for significant speedup can not be used!
https://pymoo.org/installation.html#installation

To disable this warning:
from pymoo.configuration import Configuration
Configuration.show_compile_hint = False

=============================================
n_gen |  n_eval |     fopt     |     favg    
=============================================
    1 |     100 |  0.138459616 |  2.993702771
Traceback (most recent call last):
  File "see.py", line 29, in <module>
    res       = minimize(problem, algorithm, ("n_gen", 100), verbose=True, seed=1)
  File "/home/alaya/.local/lib/python3.8/site-packages/pymoo/optimize.py", line 85, in minimize
    res = algorithm.solve()
  File "/home/alaya/.local/lib/python3.8/site-packages/pymoo/model/algorithm.py", line 226, in solve
    self._solve(self.problem)
  File "/home/alaya/.local/lib/python3.8/site-packages/pymoo/model/algorithm.py", line 321, in _solve
    self.next()
  File "/home/alaya/.local/lib/python3.8/site-packages/pymoo/model/algorithm.py", line 246, in next
    self._next()
  File "/home/alaya/.local/lib/python3.8/site-packages/pymoo/algorithms/genetic_algorithm.py", line 93, in _next
    self.off = self.mating.do(self.problem, self.pop, self.n_offsprings, algorithm=self)
  File "/home/alaya/.local/lib/python3.8/site-packages/pymoo/model/infill.py", line 40, in do
    _off = self.eliminate_duplicates.do(_off, pop, off)
  File "/home/alaya/.local/lib/python3.8/site-packages/pymoo/model/duplicate.py", line 26, in do
    pop = pop[~self._do(pop, None, np.full(len(pop), False))]
  File "/home/alaya/.local/lib/python3.8/site-packages/pymoo/model/duplicate.py", line 75, in _do
    D = self.calc_dist(pop, other)
  File "/home/alaya/.local/lib/python3.8/site-packages/pymoo/model/duplicate.py", line 66, in calc_dist
    D = cdist(X, X)
  File "/home/alaya/.local/lib/python3.8/site-packages/pymoo/util/misc.py", line 90, in cdist
    return scipy.spatial.distance.cdist(A, B, **kwargs)
  File "/home/alaya/.local/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2954, in cdist
    return cdist_fn(XA, XB, out=out, **kwargs)
ValueError: Unsupported dtype object
```

**Comment by julesy89** [comment]
Thanks for reporting this issue!

Adding a cast of the array before calling scipy resolves the issue (`pymoo.util.misc.cdist`).

```
def cdist(A, B, **kwargs):
    return scipy.spatial.distance.cdist(A.astype(float), B.astype(float), **kwargs)

```

**Comment by jennywang123** [comment]
Could you update pymoo release for this issue so we do not have to modify the source code?

Thank you
Jenny

**Comment by julesy89** [comment]
I am planning to create a bigger release soon. I am about to automate the release process to update such fixes quicker.
Currently, it is a time-consumer process because of all the compiled packages for Windows and Mac for different Python version.

Until the next release please use the code below which basically is the same fix without changing any code in the framework.

```
import numpy as np
from pymoo.model.duplicate import DefaultDuplicateElimination
from pymoo.model.problem import Problem
from pymoo.optimize import minimize
from pymoo.factory import get_algorithm
from pymoo.operators.mixed_variable_operator import MixedVariableMutation
from pymoo.factory import get_mutation
from scipy.spatial.distance import cdist


class MyDuplicatedElimination(DefaultDuplicateElimination):

    def calc_dist(self, pop, other=None):
        X = self.func(pop).astype(float)

        if other is None:
            D = cdist(X, X)
            D[np.triu_indices(len(X))] = np.inf
        else:
            _X = self.func(other).astype(float)
            D = cdist(X, _X)

        return D


class MyProblem(Problem):
    def __init__(self):
        super().__init__(n_var=2,
                         n_obj=1,
                         n_constr=0,
                         xl=np.array([-2, -2]),
                         xu=np.array([2, 2]),
                         )

    def _evaluate(self, x, out, *args, **kwargs):
        out['F'] = (x ** 2).sum(axis=1, keepdims=True)


mask = ['real', 'real']
mutation = MixedVariableMutation(mask, {
    'real': get_mutation('real_pm', eta=20),
    'int': get_mutation('int_pm', eta=20)
})
problem = MyProblem()
algorithm = get_algorithm('ga', pop_size=100, mutation=mutation, eliminate_duplicates=MyDuplicatedElimination())
res = minimize(problem, algorithm, ("n_gen", 100), verbose=True, seed=1)
print(res.X)

```

**Comment by jennywang123** [comment]
Thank you. Looking forward to the new bigger release! 👍
