### ISSUE TITLE
NSGA2 Example crashes

### ISSUE THREAD

**Issue by MatthiasJakobs** [msu-coinlab/pymoo#170]
When I run the NSGA 2 example below using my configuration of packages (also below), I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    verbose=False)
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/optimize.py", line 85, in minimize
    res = algorithm.solve()
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/model/algorithm.py", line 226, in solve
    self._solve(self.problem)
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/model/algorithm.py", line 321, in _solve
    self.next()
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/model/algorithm.py", line 243, in next
    self.initialize()
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/model/algorithm.py", line 215, in initialize
    self._initialize()
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/algorithms/genetic_algorithm.py", line 86, in _initialize
    n_min_infeas_survive=self.min_infeas_pop_size)
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/model/survival.py", line 120, in do
    survivors = self._do(problem, pop, n_survive, **kwargs)
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/algorithms/nsga2.py", line 134, in _do
    fronts = self.nds.do(F, n_stop_if_ranked=n_survive)
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/util/nds/non_dominated_sorting.py", line 20, in do
    func = load_function(self.method)
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/util/function_loader.py", line 84, in load_function
    return FunctionLoader.get_instance().load(func_name, _type=_type)
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/util/function_loader.py", line 77, in load
    module = importlib.import_module(func)
  File "/home/matty/.miniconda3/envs/pruning/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/matty/.miniconda3/envs/pruning/lib/python3.7/site-packages/pymoo/cython/non_dominated_sorting.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```

Code to reproduce:

```python
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_problem
from pymoo.optimize import minimize
from pymoo.visualization.scatter import Scatter

problem = get_problem("zdt1")

algorithm = NSGA2(pop_size=100)

res = minimize(problem,
               algorithm,
               ('n_gen', 200),
               seed=1,
               verbose=False)
```

`requirements.txt`:

```
appdirs==1.4.4
autograd==1.3
certifi==2021.5.30
cloudpickle==1.6.0
cma==2.7.0
cycler==0.10.0
distlib==0.3.1
filelock==3.0.12
future==0.18.2
importlib-metadata==1.7.0
joblib==1.0.1
kiwisolver==1.3.1
llvmlite==0.36.0
matplotlib==3.4.2
mkl-fft==1.3.0
mkl-random @ file:///tmp/build/80754af9/mkl_random_1618853974840/work
mkl-service==2.3.0
numba==0.53.1
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1620831194891/work
pandas==1.3.0
pbr==5.5.0
Pillow==8.3.1
pymoo==0.4.2.2
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2021.1
scikit-learn==0.24.2
scipy==1.7.0
shap==0.39.0
six @ file:///tmp/build/80754af9/six_1623709665295/work
slicer==0.0.7
stevedore==3.2.2
threadpoolctl==2.2.0
tqdm==4.61.2
virtualenv==20.0.31
virtualenv-clone==0.5.4
virtualenvwrapper==4.8.4
zipp==3.1.0
```

**Comment by julesy89** [comment]
What numpy version are you using?

**Comment by MatthiasJakobs** [comment]
1.20.2

**Comment by gitphilip** [comment]
This issue was closed without providing a solution.

I do have this problem still, though. I am using pymoo 0.4.2.1 and cannot upgrade for developmental reasons.

Do we know the reason this happens and what I can do to mitigate this? Many thanks!

**Comment by julesy89** [comment]
I think this is related to the compiled libraries. If you can upgrade (and I would be curious if this works for you in the 0.5.0 version anyway) you can clone the old repo and compile the libraries on your system.
See the `Compilation` tutorial under https://pymoo.org/installation.html.

**Comment by gitphilip** [comment]
Thanks for your reply! 0.5.0 works in fact. I could upgrade my code to this version, however, the package names and class structure changed apparently, which would mean quite some effort and possibly breaking things (which I try to avoid currently :-) ). 

So, if I understand correctly, the solution would be to manually compile the cython libraries using the old clone of the repository (instead of installing it via pip)?

**Comment by julesy89** [comment]
Try this quick fix: 

Before running your algorithm execute:
`FunctionLoader().get_instance().is_compiled = False``

Does this work for you?

**Comment by gitphilip** [comment]
> 

It does indeed! Great, thank you so much :-)

And I also wanted to thank you in general for your wonderful project. I really appreciate it. Keep up the good work!!
