### ISSUE TITLE
Question: verbose flag in minimize & elementwise_evaluation + threads

### ISSUE THREAD

**Issue by i-a-morozov** [msu-coinlab/pymoo#22]
Hi,

I've modified the getting-started example for elementwise evaluation and parallelization with threads.
The result is correct, but it doesn't work with verbose flag in minimize.
Can you reproduce this behavior?
How can I monitor evaluation in this case?

Code (comment/uncomment verbose in minimize):
```python
import autograd.numpy as anp
import numpy as np
from pymoo.model.problem import Problem

# Define problem parameters
knobs=2                    # number of variables (decision space dimension)
number_of_objectives=2     # number of objectives (all to be minimized)
number_of_constraints=2    # number of constraints (all have the form const_i <= 0)
lbound=[-2,-2]             # set lower bounds for all decision variables
ubound=[+2.+2]             # set upper bounds for all decision variables
number_of_threads=4        # number of threads

# Define problem
class task(Problem):
    
    # Set main parameters
    def __init__(self,**kwargs):
        super().__init__(
            n_var=knobs,                  
            n_obj=number_of_objectives,
            n_constr=number_of_constraints,
            xl=lbound,
            xu=ubound,
            elementwise_evaluation=True,
            **kwargs
            )
        
    # Set objectives and constraints
    def _evaluate(self,x,out,*args,**kwargs):
        # Define objective functions and constraints
        f1 = x[0]**2+x[1]**2
        f2 = (x[0]-1)**2+x[1]**2
        g1 = 2*(x[0]-0.1)*(x[0]-0.9)/0.18
        g2 = -20*(x[0]-0.4)*(x[0]-0.6)/4.8
        out["F"] = [f1,f2]
        out["G"] = [g1,g2]
    
# Set problem    
problem = task(parallelization=("threads",number_of_threads))

#  Algorithm
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_sampling, get_crossover, get_mutation
algorithm = NSGA2(
    pop_size=50,
    n_offsprings=20,
    sampling=get_sampling("real_random"),
    crossover=get_crossover("real_sbx",prob=0.9,eta=15),
    mutation=get_mutation("real_pm",eta=20),
    eliminate_duplicates=True
)

# Termination
from pymoo.factory import get_termination
termination = get_termination("n_gen",30)

# Optimize (works OK without verbose)
from pymoo.optimize import minimize
res = minimize(problem,algorithm,termination,seed=1,save_history=True,verbose=True)

# Plot
import matplotlib.pyplot as plt
from pymoo.visualization.scatter import Scatter
plot = Scatter(title = "Design Space", axis_labels="x")
plot.add(res.X, s=30, facecolors='none', edgecolors='r')
plot.do()
plot.apply(lambda ax: ax.set_xlim(-0.5, 1.5))
plot.apply(lambda ax: ax.set_ylim(-2, 2))
plt.show()

plot = Scatter(title = "Objective Space")
plot.add(res.F)
plot.do()
plt.show()
```

Errors:

```
Traceback (most recent call last):
  File "template.py", line 59, in <module>
    res = minimize(problem,algorithm,termination,seed=1,save_history=True,verbose=True)
  File "/home/imorozov/.conda/envs/pymoo/lib/python3.7/site-packages/pymoo/optimize.py", line 58, in minimize
    res = algorithm.solve()
  File "/home/imorozov/.conda/envs/pymoo/lib/python3.7/site-packages/pymoo/model/algorithm.py", line 154, in solve
    self._solve(self.problem)
  File "/home/imorozov/.conda/envs/pymoo/lib/python3.7/site-packages/pymoo/model/algorithm.py", line 203, in _solve
    self._each_iteration(self, first=True)
  File "/home/imorozov/.conda/envs/pymoo/lib/python3.7/site-packages/pymoo/model/algorithm.py", line 218, in _each_iteration
    disp = self.func_display_attrs(self.problem, self.evaluator, self, self.pf)
  File "/home/imorozov/.conda/envs/pymoo/lib/python3.7/site-packages/pymoo/util/display.py", line 72, in disp_multi_objective
    attrs.append(('igd', format_float(IGD(pf).calc(F[feasible])), width))
  File "/home/imorozov/.conda/envs/pymoo/lib/python3.7/site-packages/pymoo/model/indicator.py", line 49, in calc
    return self._calc(F)
  File "/home/imorozov/.conda/envs/pymoo/lib/python3.7/site-packages/pymoo/performance_indicator/distance_indicator.py", line 26, in _calc
    D = vectorized_cdist(self.pf, F, func_dist=self.dist_func, norm=self.range)
  File "/home/imorozov/.conda/envs/pymoo/lib/python3.7/site-packages/pymoo/util/misc.py", line 102, in vectorized_cdist
    D = func_dist(u, v, **kwargs)
  File "/home/imorozov/.conda/envs/pymoo/lib/python3.7/site-packages/pymoo/performance_indicator/distance_indicator.py", line 8, in euclidean_distance
    return np.sqrt((((a - b) / norm) ** 2).sum(axis=1))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

```

**Comment by julesy89** [comment]
For me the code runs without any problem. 
Please give me some more information:

- Operating System
- Python Version
- NumPy Version
- Pymoo Version

**Comment by i-a-morozov** [comment]
Please see the info below.
Also, still got errors even when with parallelization removed.

```python
problem = task()
``` 

**Operating System**
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
**Python Version**
```
Python 3.7.0
```
**pip list**
```
Package               Version  
--------------------- ---------
aiohttp               3.6.1    
async-timeout         3.0.1    
attrs                 19.1.0   
autograd              1.3      
bleach                3.1.0    
certifi               2019.9.11
chardet               3.0.4    
cycler                0.10.0   
Cython                0.29.13  
docutils              0.15.2   
Forthon               0.8.35   
future                0.17.1   
idna                  2.8      
kiwisolver            1.1.0    
matplot               0.1.9    
matplotlib            3.1.1    
mkl-fft               1.0.14   
mkl-random            1.1.0    
mkl-service           2.3.0    
multidict             4.5.2    
numpy                 1.16.5   
oauthlib              3.1.0    
pip                   19.2.3   
pkginfo               1.5.0.1  
Pygments              2.4.2    
pyloco                0.0.139  
pymoo                 0.3.1    
pyparsing             2.4.2    
python-dateutil       2.8.0    
pytz                  2019.2   
pyzmq                 18.1.0   
readme-renderer       24.0     
requests              2.22.0   
requests-toolbelt     0.9.1    
scipy                 1.3.1    
setuptools            41.2.0   
SimpleWebSocketServer 0.1.1    
six                   1.12.0   
tqdm                  4.36.1   
twine                 2.0.0    
typing                3.7.4.1  
urllib3               1.25.6   
ushlex                0.99.1   
webencodings          0.5.1    
websocket-client      0.56.0   
wheel                 0.33.6   
wolframclient         1.1.0    
yarl                  1.3.0    
zmq                   0.0.0
```

**Comment by julesy89** [comment]
Thanks for pointing it out.
I just pushed something to Github. Can you install the newest version in the Master branch and see if that works for you now?
pymoo-0.3.2.dev0

Otherwise, a quick fix is to modify the minimize line 

`res = minimize(problem,algorithm,termination,seed=1,save_history=True,verbose=True,pf=None)`

The problem is that no Pareto front is found (because not provided), but it tries to calculate IGD.

**Comment by i-a-morozov** [comment]
Thank you, now it works.
Is it possible to customize verbose info? 
I need to print generation all individuals and corresponding objectives and constraints after each generation?
My objective functions take a long time to compute and I would like to keep track of all evaluations.

**Comment by julesy89** [comment]
You can not directly customize verbose. However, you can provide a callback method to the algorithm object which is executed in the end of each generation. 
You can then use the display function which we provide or write your own.

Instead of printing all values, I recommend you to store the values in a file. You can either store the whole population each generation or another possibility is you store all X, F and G values every time the evaluation function in the problem class is called.


```
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_problem
from pymoo.optimize import minimize
from pymoo.visualization.scatter import Scatter


def my_callback(algorithm):
    disp = algorithm.func_display_attrs(algorithm.problem, algorithm.evaluator, algorithm, algorithm.pf)
    print("My Custom Output: ", end='')
    algorithm._display(disp)


problem = get_problem("zdt2")

algorithm = NSGA2(pop_size=100, elimate_duplicates=True, callback=my_callback)

res = minimize(problem,
               algorithm,
               ('n_gen', 200),
               seed=1,
               verbose=False)

plot = Scatter()
plot.add(problem.pareto_front(), plot_type="line", color="black", alpha=0.7)
plot.add(res.F, color="red")
plot.show()

```
