### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by twodonkeys** [msu-coinlab/pymoo#41]
when i run this flowing the tutorial：[https://pymoo.org/getting_started.html#Multi-Objective-Optimization](https://pymoo.org/getting_started.html#Multi-Objective-Optimization)；
i get a misstake describ as “ValueError: negative dimensions are not allowed”

C:\Users\hero\Anaconda3\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 7154 --file C:/Users/hero/PycharmProjects/GCS/test_pymoo.py
pydev debugger: process 3788 is connecting

Connected to pydev debugger (build 182.4505.26)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/hero/PycharmProjects/GCS/test_pymoo.py", line 58, in <module>
    verbose=True
  File "C:\Users\hero\Anaconda3\lib\site-packages\pymoo\optimize.py", line 58, in minimize
    res = algorithm.solve()
  File "C:\Users\hero\Anaconda3\lib\site-packages\pymoo\model\algorithm.py", line 168, in solve
    self._solve(self.problem)
  File "C:\Users\hero\Anaconda3\lib\site-packages\pymoo\model\algorithm.py", line 218, in _solve
    self._initialize()
  File "C:\Users\hero\Anaconda3\lib\site-packages\pymoo\algorithms\genetic_algorithm.py", line 87, in _initialize
    pop = self.sampling.do(self.problem, self.pop_size, pop=pop, algorithm=self)
  File "C:\Users\hero\Anaconda3\lib\site-packages\pymoo\model\sampling.py", line 41, in do
    val = self._do(problem, n_samples, **kwargs)
  File "C:\Users\hero\Anaconda3\lib\site-packages\pymoo\operators\sampling\random_sampling.py", line 18, in _do
    val = np.random.random((n_samples, problem.n_var))
  File "mtrand.pyx", line 861, in mtrand.RandomState.random_sample
  File "mtrand.pyx", line 167, in mtrand.cont0_array
ValueError: negative dimensions are not

**Comment by twodonkeys** [comment]
this is the code ，flowing the tutorial [https://pymoo.org/getting_started.html#Multi-Objective-Optimization](https://pymoo.org/getting_started.html#Multi-Objective-Optimization)


import autograd.numpy as anp #autograd自动求导库
import numpy as np
from pymoo.util.misc import stack
from pymoo.model.problem import Problem
from pymoo.algorithms.nsga2 import NSGA2
from pymoo.factory import get_sampling,get_crossover,get_mutation
from pymoo.factory import get_termination
from pymoo.optimize import minimize
##第一步、定义问题
class MyProblem(Problem):
    def __ini__(self):
        super().__init__(n_var=2,
                         n_obj=2,
                         n_constr=2,
                         xl=anp.array([-2,-2]),
                         xu=anp.array([2,2]))

    def _evaluate(self,x,out,*args,**kwargs):
        #目标函数
        f1=x[:,0]**2+x[:,1]**2
        f2=(x[:,0]-1)**2+x[:,1]**2

        #约束条件
        g1=2*(x[:,0]-0.1)*(x[:,0]-0.9)/0.18
        g2=-20*(x[:,0]-0.4)*(x[:,0]-0.6)/4.8

        out["F"]=anp.column_stack([f1,f2])
        out["G"]=anp.column_stack([g1,g2])
problem=MyProblem()
##第二步、初始化算法
algorithm=NSGA2(
    pop_size=40,
    n_offsprings=10,
    sampling=get_sampling("real_random"),
    crossover=get_crossover("real_sbx",prob=0.9,eta=15),
    mutation=get_mutation("real_pm",eta=20),
    eliminate_duplicates=True
)
##第三步、定义终止条件
termination=get_termination("n_gen",40)

##第四步、优化
res=minimize(problem,
             algorithm,
             termination,
             seed=1,
             pf=problem.pareto_front(use_cache=False),
             save_history=True,
             verbose=True
             )
print(res)
